name: Load Env
description: Action to Load Environment Variables
     
runs:
  using: "composite"
  steps:
      - name: "Launch action"
        id: action-env
        uses: Steph0/dotenv-configserver@main
        with:
          repository: "the-iron-bank-of-braavos/load-env"
          token: "${{ secrets.GITHUB_TOKEN }}"
      
      # You should see your .env config in 'env'
      - name: "See exported values"
        run: env
        shell: bash
        
      - name: Test
        run: |
          echo ${{ env.AUTHOR }}
          echo ${{ env.VERSION }}
          echo ${{ steps.action-env.outputs.AUTHOR }}
          echo ${{ steps.action-env.outputs.VERSION }}
        shell: bash

